# PostgreSQL. Versions 8.2 and up are supported.

default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: conconcretoapp_development
  username: danielllano
  #password

test:
  <<: *default
  database: conconcretoapp_test
  username: danielllano
  #password

production:
  <<: *default
  database: conconcretoapp_production
  # username: danielllano
  # password: <%= ENV['CONCONCRETOAPP_DATABASE_PASSWORD'] %>
